// Las sondas con las que se mide, contra un motor de verdad, si el índice único CONDICIONADO que
// emite `build` sostiene la garantía que el diseño declaró.
//
// Por qué hace falta una red propia. El appendix `db/partial-indexes.sql` es la única fuente de un
// invariante del diseño —«como máximo una fila por esta clave mientras esté en este estado»— y
// **ninguna de las redes que ya existen lo mira**: los tests comparan cadenas, `java-syntax`
// tokeniza Java (esto no es Java), `compile-check` invoca a javac (esto no pasa por javac) y el
// arnés de integración no lo ejercita porque el perfil `test` corre sobre H2, que no lo puede
// ejecutar. O sea que hasta aquí el índice se juzgaba leyéndolo.
//
// Y el modo de fallo es el de siempre en esta capa, el silencioso: un índice que se CREA sin error
// y no casa con ninguna fila deja el invariante sin efecto, y no lo delata el arranque, ni el
// baseline, ni ningún escenario — la ausencia de un rechazo no falla ninguna aserción. Ya ocurrió,
// y durante meses: el predicado iba en minúsculas (`= 'active'` contra una columna que guarda
// `ACTIVE`), así que el índice indexaba cero filas. Lo destapó una persona leyendo, no la suite.
//
// ─── Las cuatro preguntas, y por qué son esas ────────────────────────────────
//
// Ninguna es sobre la sintaxis: eso ya lo dice el motor al crear el índice. Son sobre el EFECTO, y
// cada una cierra una forma distinta de estar mal:
//
//   idempotencia   el appendix se ejecuta en CADA arranque con `continue-on-error: false`, así
//                  que un guardia que no reconozca su propio índice mata el segundo arranque.
//                  Es la mitad que solo se ve ejecutando DOS veces.
//   exclusividad   dos filas con la misma clave DENTRO de la condición: la segunda tiene que
//                  morir. Es la garantía entera, y la que un predicado que no casa pierde en
//                  silencio.
//   historia       N filas con la misma clave FUERA de la condición: todas tienen que entrar.
//                  Es lo que separa el índice condicionado de una constraint única normal — que
//                  también pasaría `exclusividad` y prohibiría además las versiones históricas,
//                  o sea el invariante CONTRARIO al declarado.
//   independencia  otra clave puede tener la suya dentro de la condición. Sin esto, un índice
//                  que restringiera de más pasaría las tres anteriores.
//
// ─── El sustrato ────────────────────────────────────────────────────────────
//
// El índice necesita una tabla debajo, y aquí no hay JDK que arranque Hibernate. La tabla se monta
// con las columnas que el PROPIO spec nombra —no con unas derivadas por segunda vez—, que es lo
// que impide que el check acabe midiendo una copia de sí mismo: si el spec nombrara una columna
// que la entidad no tiene, el `CREATE INDEX` seguiría casando con el sustrato y el check saldría
// verde sobre un índice que en el servicio de verdad no se puede crear. Con esta forma no puede:
// las dos mitades salen del mismo sitio, así que lo que se mide es el EFECTO del índice, y el
// nombre de la columna lo mide `mapping-check`, que es de quien es esa pregunta.

import { partialIndexSpecs, sqlLiteral } from '../scaffold/migrations.js';
import { partialDocumentIndexSpecs } from '../scaffold/document-indexes.js';

/** Los valores con los que se pueblan las columnas de la clave. Dos juegos: la misma y otra. */
const KEY_A = (n) => `keel_a${n}`;
const KEY_B = (n) => `keel_b${n}`;

/**
 * El valor que deja a la fila FUERA de la condición. Tiene que ser del mismo tipo que el de
 * dentro —la columna es una sola— y distinto de él, que es lo único que hace fallable el caso de
 * las versiones históricas: con el mismo valor, ese caso mediría otra vez la exclusividad.
 */
export function outsideValue(stored) {
  if (typeof stored === 'boolean') return !stored;
  if (typeof stored === 'number') return stored + 1;
  return `${stored}_KEEL_OFF`;
}

/** El tipo de la columna de la condición, que es el único que no puede ser texto a ciegas. */
function whenColumnType(stored) {
  if (typeof stored === 'boolean') return 'BOOLEAN';
  if (typeof stored === 'number') return 'INTEGER';
  return 'VARCHAR(64)';
}

/**
 * El índice condicionado que esta corrida mide. Uno solo y el primero: el check existe para
 * juzgar el MECANISMO, y un diseño con dos índices condicionados no lo ejercita más que con uno.
 */
export function indexSubject(model) {
  const [spec] = partialIndexSpecs(model);
  return spec ?? null;
}

/**
 * La tabla mínima sobre la que vive el índice. Sin clave primaria a propósito: no hace falta para
 * lo que se mide, y una la tendría que escribir cada motor a su manera (`AUTO_INCREMENT` no es
 * `GENERATED BY DEFAULT AS IDENTITY`), que es superficie del check y no del generador.
 */
export function substrateSql(spec) {
  const columns = [
    ...spec.columnList.map((column) => `  ${column} VARCHAR(64) NOT NULL`),
    `  ${spec.whenColumn} ${whenColumnType(spec.stored)} NOT NULL`
  ];
  return [`DROP TABLE IF EXISTS ${spec.table};`, `CREATE TABLE ${spec.table} (\n${columns.join(',\n')}\n);`];
}

function insert(spec, keyOf, whenValue) {
  const values = [...spec.columnList.map((_, n) => sqlLiteral(keyOf(n))), sqlLiteral(whenValue)];
  const columns = [...spec.columnList, spec.whenColumn].join(', ');
  return `INSERT INTO ${spec.table} (${columns}) VALUES (${values.join(', ')});`;
}

/**
 * Las aserciones, en orden y con su desenlace esperado. `expect: 'reject'` significa que la
 * sentencia tiene que FALLAR: es la única forma que tiene un índice de decir que sostiene algo.
 */
export function assertions(spec) {
  const inside = spec.stored;
  const outside = outsideValue(inside);
  return [
    {
      id: 'exclusividad',
      title: `dos filas con la misma clave con ${spec.when.field} dentro de la condición: la segunda muere`,
      steps: [
        { sql: insert(spec, KEY_A, inside), expect: 'ok' },
        { sql: insert(spec, KEY_A, inside), expect: 'reject' }
      ]
    },
    {
      id: 'historia',
      title: 'tres versiones históricas con esa misma clave entran las tres',
      // Tres y no dos: con dos, un índice que restringiera las de fuera de dos en dos pasaría.
      steps: [
        { sql: insert(spec, KEY_A, outside), expect: 'ok' },
        { sql: insert(spec, KEY_A, outside), expect: 'ok' },
        { sql: insert(spec, KEY_A, outside), expect: 'ok' }
      ]
    },
    {
      id: 'independencia',
      title: 'otra clave puede tener la suya dentro de la condición',
      steps: [{ sql: insert(spec, KEY_B, inside), expect: 'ok' }]
    }
  ];
}

// ─── La opacidad del índice a la introspección JDBC ─────────────────────────
//
// La pregunta que le faltaba a este check, y que costó una corrida entera de diagnóstico: **¿este
// índice tiene alguna key part sin nombre de columna?**
//
// Importa porque con `ddl-auto: update` Hibernate introspecciona TODOS los índices de la tabla
// —también los que no declaró— para reconciliar sus `@UniqueConstraint`, y una key part sin
// nombre le llega como null y aborta la carga entera del ApplicationContext. No en el primer
// arranque, sino en el segundo.
//
// La respuesta que se exige es CERO, sin excepción. Hubo una versión de esta sonda que admitía
// «opaco pero mitigado» —contrastaba la opacidad contra
// `hibernate.schema_update.unique_constraint_strategy: SKIP` en el perfil `local`— y se endureció
// al medir esa mitigación: en MySQL los `@UniqueConstraint` se crean por `ALTER TABLE` dentro de
// esa misma reconciliación, así que saltársela no los conserva, IMPIDE QUE EXISTAN (ver
// `migrations.js` § Por qué NO hay ningún ajuste de Hibernate). O sea que la mitigación cambiaba
// un fallo ruidoso por uno silencioso, y una sonda que la aceptara estaría bendiciendo la pérdida
// de la clave natural del agregado. Un índice opaco no se mitiga: no se emite.
//
// La pregunta se hace en el idioma de cada motor a propósito. No hay forma portable de
// preguntarla, y componerla a ojo daría siempre cero —que es indistinguible de «no es opaco»—.
// La pregunta se le hace a cada motor en SU idioma a propósito. No hay forma portable de hacerla, y
// componerla a ojo daría siempre cero —que es indistinguible de «no es opaco»—.
//
// Y hay TRES situaciones, no dos. La tercera es la que impide que un motor nuevo se cuele sin
// decidir, igual que la matriz de paridad impide que se cuele sin fila:
//
//   consulta        el motor PUEDE tener key parts sin nombre: se le pregunta y se exige cero.
//   no puede serlo  declarado, con su porqué. El caso no se mide: ni verde ni rojo.
//   sin declarar    nada. El runner lo pone en KO, que es lo correcto — no se sabe.
const OPACITY = {
  // COLUMN_NAME null es literalmente lo que responde MySQL para una key part funcional; es lo mismo
  // que ve `DatabaseMetaData#getIndexInfo`, que es quien se lo pasa a Hibernate.
  mysql: {
    query: (spec) =>
      'SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE()' +
      ` AND TABLE_NAME = ${sqlLiteral(spec.tableName)} AND INDEX_NAME = ${sqlLiteral(spec.name)}` +
      ' AND COLUMN_NAME IS NULL'
  },
  // En PostgreSQL el índice se condiciona con un predicado (`indpred`) sobre columnas REALES: lo que
  // haría opaco al índice sería una key part por expresión (`indexprs`), y no la hay. Preguntar por
  // el predicado daría siempre «opaco» y exigiría una mitigación que aquí no hace falta.
  postgresql: {
    query: (spec) =>
      `SELECT COUNT(*) FROM pg_index WHERE indexrelid = ${sqlLiteral(spec.name)}::regclass AND indexprs IS NOT NULL`
  },
  // SQL Server condiciona con un índice FILTRADO (`WHERE …`) sobre columnas reales, y no admite key
  // parts por expresión: sus índices son siempre sobre columnas, así que ninguna puede llegar sin
  // nombre a `getIndexInfo`. Se declara en vez de emitir una consulta porque su respuesta sería
  // cero POR CONSTRUCCIÓN, y una red que no puede ponerse roja no mide nada — fingirla sería peor
  // que no tenerla.
  //
  // El riesgo, dicho en voz alta: si el motor ganara índices por expresión y algún dialecto los
  // usara, esto dejaría de ser cierto y nadie se enteraría. Es una afirmación sobre el motor, no
  // una medición, y por eso lleva su porqué escrito.
  //
  // Ojo con lo que NO sirve aquí: contar columnas COMPUTADAS (`sys.columns.is_computed`) fue la
  // primera idea y es un falso positivo — una columna computada de SQL Server tiene nombre, así
  // que el driver lo devuelve y el índice no es opaco.
  sqlserver: {
    cannotBeOpaque:
      'sus índices son siempre sobre columnas —no admite key parts por expresión—, así que ninguna ' +
      'puede llegar sin nombre a DatabaseMetaData#getIndexInfo'
  }
  // mariadb y oracle NO se declaran a propósito: hoy son degradaciones anunciadas (no se emite
  // índice condicionado) y el runner aborta antes de llegar aquí. El día que alguien les escriba un
  // dialecto, caerán en «sin declarar» y tendrá que decidir — que es exactamente lo que se quiere.
};

/**
 * Qué se puede decir de la opacidad del índice en ESTE motor:
 *
 *   `{ query }`          la consulta con la que preguntárselo.
 *   `{ cannotBeOpaque }` el motivo por el que no puede serlo.
 *   `null`               no se sabe: el motor no lo declara.
 */
export const opacityOf = (database, spec) => {
  const entry = OPACITY[database];
  if (!entry) return null;
  return entry.query ? { query: entry.query(spec) } : { cannotBeOpaque: entry.cannotBeOpaque };
};

/**
 * Las sentencias del appendix, contadas. Sirve para dos cosas —saber si el motor emitió algo, y
 * poder decirlo por pantalla— y para NINGUNA más: el runner manda el archivo ENTERO en una sola
 * llamada, no sentencia a sentencia.
 *
 * Esa distinción costó una pasada en rojo y conviene no perderla. En MySQL el appendix son cuatro
 * sentencias planas que se comunican por una variable de usuario (`@keel_index_ddl`), y una
 * variable de usuario **muere con la sesión**. Un runner que ejecutara `CLI -e <sentencia>` una
 * por una abriría una conexión por sentencia, así que el `PREPARE` recibiría NULL y fallaría con
 * un error de sintaxis que no habla del índice ni del generador — un rojo que acusa al código
 * correcto. `spring.sql.init` sí las corre todas sobre la misma conexión, o sea que el runner
 * fiel es el que manda el archivo de una pieza; y como efecto colateral, lo que se ejecuta es
 * literalmente el contenido del archivo y no una segunda redacción suya.
 */
export function statementsOf(appendix) {
  const out = [];
  let current = [];
  for (const line of appendix.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('--')) continue;
    current.push(line);
    if (trimmed.endsWith(';')) {
      out.push(current.join('\n').trim().replace(/;$/, ''));
      current = [];
    }
  }
  return out;
}

// ─── La rama documental ─────────────────────────────────────────────────────
//
// El mismo mecanismo, otro almacén y —esto es lo que cambia la forma del check— otro ARTEFACTO.
// En relacional el índice condicionado vive en un `.sql` que el motor sabe ejecutar solo, así que
// la rama entera se mide sin JDK. En Mongo vive en `MongoIndexConfig.java`, y renderizar aquí una
// copia en mongosh de sus `createIndex` sería exactamente el defecto que tuvo `mongo-check` meses
// en verde: medir una copia de sí mismo. Por eso lo que se ejecuta es la CLASE GENERADA, y por eso
// esta rama sí necesita JDK.
//
// Las cuatro preguntas se conservan con sus ids —una que existiera en una rama y no en la otra es
// una asimetría silenciosa, que es la forma exacta que tenían los ocho defectos que motivaron la
// matriz de paridad—, pero dos cosas cambian y ninguna es cosmética:
//
//   El SUSTRATO desaparece. No hay DDL que montar: la colección se vacía y ya. Eso es una VENTAJA
//   sobre la rama relacional, donde la tabla mínima no puede llevar la clave natural completa —
//   aquí conviven los dos índices, así que `independencia` mide de verdad que el condicionado no
//   desplazó al natural.
//
//   Un rechazo tiene que decir QUÉ índice lo produjo. Con los dos índices vivos sobre la misma
//   colección, un `E11000` no distingue por sí solo al condicionado del natural, y `exclusividad`
//   podría salir verde porque rechazó el natural —o sea sin haber medido nada—. De ahí que cada
//   paso `reject` nombre el índice que le toca, y que los documentos varíen la clave natural
//   donde el caso lo exige.

/** Relleno de las columnas de la clave natural que el índice condicionado NO nombra. */
const VERSION = (n) => `keel_v${n}`;

/**
 * El índice condicionado documental que esta corrida mide. Uno solo y el primero, por lo mismo
 * que en la rama relacional: el check juzga el MECANISMO.
 */
export function documentIndexSubject(model) {
  const [spec] = partialDocumentIndexSpecs(model);
  return spec ?? null;
}

/**
 * Un documento CRUDO —sin pasar por el mapeo— con la clave del índice condicionado, el valor de
 * la condición y, si el caso lo pide, una clave natural propia.
 *
 * Que sea crudo es deliberado y es lo mismo que hace el sustrato relacional al montar su tabla
 * mínima: deja los casos de efecto independientes de los campos obligatorios de la entidad. El
 * único caso que SÍ pasa por el mapeo es el del literal, y va aparte porque mide otra cosa.
 */
function documentOf(spec, keyOf, whenValue, versionOf) {
  const pairs = spec.paths.map((path, n) => [path, keyOf(n)]);
  for (const path of spec.naturalKeyPaths) {
    if (!spec.paths.includes(path)) pairs.push([path, versionOf]);
  }
  pairs.push([spec.partialFilter.path, whenValue]);
  return pairs;
}

/**
 * Las aserciones documentales, con los mismos ids que las relacionales. `expect: 'reject'` trae
 * además el índice que tiene que producir el rechazo: sin eso, el natural podría estar contestando
 * por el condicionado.
 *
 * Cada aserción empieza con la colección VACÍA —el runner la limpia entre una y otra, preservando
 * los índices—, y eso no es higiene sino corrección: aquí la clave natural está viva, así que un
 * documento que `exclusividad` dejó puesto haría que `historia` muriera por el índice natural. En
 * la rama relacional el sustrato es una tabla desnuda y el problema no existe.
 */
export function documentAssertions(spec) {
  const inside = spec.partialFilter.equals;
  const outside = outsideValue(inside);
  const natural = spec.naturalKeyName;
  return [
    {
      id: 'exclusividad',
      title: `dos documentos con la misma clave con ${spec.when.field} dentro de la condición: el segundo muere`,
      steps: [
        // Versiones DISTINTAS a propósito: con la misma, quien rechazaría es la clave natural y
        // el caso saldría verde sin haber ejercitado el índice condicionado.
        { doc: documentOf(spec, KEY_A, inside, VERSION(0)), expect: 'ok' },
        { doc: documentOf(spec, KEY_A, inside, VERSION(1)), expect: 'reject', index: spec.name }
      ]
    },
    {
      id: 'historia',
      title: 'tres versiones históricas con esa misma clave entran las tres',
      // Tres y no dos, igual que en la rama relacional: con dos, un índice que restringiera las
      // de fuera de dos en dos pasaría.
      steps: [
        { doc: documentOf(spec, KEY_A, outside, VERSION(0)), expect: 'ok' },
        { doc: documentOf(spec, KEY_A, outside, VERSION(1)), expect: 'ok' },
        { doc: documentOf(spec, KEY_A, outside, VERSION(2)), expect: 'ok' }
      ]
    },
    {
      id: 'independencia',
      title: 'otra clave tiene la suya dentro de la condición, y la clave natural sigue restringiendo',
      steps: [
        { doc: documentOf(spec, KEY_B, inside, VERSION(0)), expect: 'ok' },
        // La otra mitad, y la que se perdería sola: un índice condicionado que hubiera DESPLAZADO
        // al natural pasaría los tres casos anteriores. Versión propia, porque lo que tiene que
        // rechazar el paso siguiente es la clave natural REPETIDA y no la del paso de arriba.
        ...(natural ? [{ doc: documentOf(spec, KEY_B, outside, VERSION(1)), expect: 'ok' }] : []),
        ...(natural ? [{ doc: documentOf(spec, KEY_B, outside, VERSION(1)), expect: 'reject', index: natural }] : [])
      ]
    }
  ];
}
