// Las sondas con las que se mide, contra un motor de verdad, si el índice único CONDICIONADO que
// emite `build` sostiene la garantía que el diseño declaró.
//
// Por qué hace falta una red propia. El appendix `db/partial-indexes.sql` es la única fuente de un
// invariante del diseño —«como máximo una fila por esta clave mientras esté en este estado»— y
// **ninguna de las redes que ya existen lo mira**: los tests comparan cadenas, `java-syntax`
// tokeniza Java (esto no es Java), `compile-check` invoca a javac (esto no pasa por javac) y el
// arnés de integración no lo ejercita porque el perfil `test` corre sobre H2, que no lo puede
// ejecutar. O sea que hasta aquí el índice se juzgaba leyéndolo.
//
// Y el modo de fallo es el de siempre en esta capa, el silencioso: un índice que se CREA sin error
// y no casa con ninguna fila deja el invariante sin efecto, y no lo delata el arranque, ni el
// baseline, ni ningún escenario — la ausencia de un rechazo no falla ninguna aserción. Ya ocurrió,
// y durante meses: el predicado iba en minúsculas (`= 'active'` contra una columna que guarda
// `ACTIVE`), así que el índice indexaba cero filas. Lo destapó una persona leyendo, no la suite.
//
// ─── Las cuatro preguntas, y por qué son esas ────────────────────────────────
//
// Ninguna es sobre la sintaxis: eso ya lo dice el motor al crear el índice. Son sobre el EFECTO, y
// cada una cierra una forma distinta de estar mal:
//
//   idempotencia   el appendix se ejecuta en CADA arranque con `continue-on-error: false`, así
//                  que un guardia que no reconozca su propio índice mata el segundo arranque.
//                  Es la mitad que solo se ve ejecutando DOS veces.
//   exclusividad   dos filas con la misma clave DENTRO de la condición: la segunda tiene que
//                  morir. Es la garantía entera, y la que un predicado que no casa pierde en
//                  silencio.
//   historia       N filas con la misma clave FUERA de la condición: todas tienen que entrar.
//                  Es lo que separa el índice condicionado de una constraint única normal — que
//                  también pasaría `exclusividad` y prohibiría además las versiones históricas,
//                  o sea el invariante CONTRARIO al declarado.
//   independencia  otra clave puede tener la suya dentro de la condición. Sin esto, un índice
//                  que restringiera de más pasaría las tres anteriores.
//
// ─── El sustrato ────────────────────────────────────────────────────────────
//
// El índice necesita una tabla debajo, y aquí no hay JDK que arranque Hibernate. La tabla se monta
// con las columnas que el PROPIO spec nombra —no con unas derivadas por segunda vez—, que es lo
// que impide que el check acabe midiendo una copia de sí mismo: si el spec nombrara una columna
// que la entidad no tiene, el `CREATE INDEX` seguiría casando con el sustrato y el check saldría
// verde sobre un índice que en el servicio de verdad no se puede crear. Con esta forma no puede:
// las dos mitades salen del mismo sitio, así que lo que se mide es el EFECTO del índice, y el
// nombre de la columna lo mide `mapping-check`, que es de quien es esa pregunta.

import { partialIndexSpecs, sqlLiteral } from '../scaffold/migrations.js';

/** Los valores con los que se pueblan las columnas de la clave. Dos juegos: la misma y otra. */
const KEY_A = (n) => `keel_a${n}`;
const KEY_B = (n) => `keel_b${n}`;

/**
 * El valor que deja a la fila FUERA de la condición. Tiene que ser del mismo tipo que el de
 * dentro —la columna es una sola— y distinto de él, que es lo único que hace fallable el caso de
 * las versiones históricas: con el mismo valor, ese caso mediría otra vez la exclusividad.
 */
export function outsideValue(stored) {
  if (typeof stored === 'boolean') return !stored;
  if (typeof stored === 'number') return stored + 1;
  return `${stored}_KEEL_OFF`;
}

/** El tipo de la columna de la condición, que es el único que no puede ser texto a ciegas. */
function whenColumnType(stored) {
  if (typeof stored === 'boolean') return 'BOOLEAN';
  if (typeof stored === 'number') return 'INTEGER';
  return 'VARCHAR(64)';
}

/**
 * El índice condicionado que esta corrida mide. Uno solo y el primero: el check existe para
 * juzgar el MECANISMO, y un diseño con dos índices condicionados no lo ejercita más que con uno.
 */
export function indexSubject(model) {
  const [spec] = partialIndexSpecs(model);
  return spec ?? null;
}

/**
 * La tabla mínima sobre la que vive el índice. Sin clave primaria a propósito: no hace falta para
 * lo que se mide, y una la tendría que escribir cada motor a su manera (`AUTO_INCREMENT` no es
 * `GENERATED BY DEFAULT AS IDENTITY`), que es superficie del check y no del generador.
 */
export function substrateSql(spec) {
  const columns = [
    ...spec.columnList.map((column) => `  ${column} VARCHAR(64) NOT NULL`),
    `  ${spec.whenColumn} ${whenColumnType(spec.stored)} NOT NULL`
  ];
  return [`DROP TABLE IF EXISTS ${spec.table};`, `CREATE TABLE ${spec.table} (\n${columns.join(',\n')}\n);`];
}

function insert(spec, keyOf, whenValue) {
  const values = [...spec.columnList.map((_, n) => sqlLiteral(keyOf(n))), sqlLiteral(whenValue)];
  const columns = [...spec.columnList, spec.whenColumn].join(', ');
  return `INSERT INTO ${spec.table} (${columns}) VALUES (${values.join(', ')});`;
}

/**
 * Las aserciones, en orden y con su desenlace esperado. `expect: 'reject'` significa que la
 * sentencia tiene que FALLAR: es la única forma que tiene un índice de decir que sostiene algo.
 */
export function assertions(spec) {
  const inside = spec.stored;
  const outside = outsideValue(inside);
  return [
    {
      id: 'exclusividad',
      title: `dos filas con la misma clave con ${spec.when.field} dentro de la condición: la segunda muere`,
      steps: [
        { sql: insert(spec, KEY_A, inside), expect: 'ok' },
        { sql: insert(spec, KEY_A, inside), expect: 'reject' }
      ]
    },
    {
      id: 'historia',
      title: 'tres versiones históricas con esa misma clave entran las tres',
      // Tres y no dos: con dos, un índice que restringiera las de fuera de dos en dos pasaría.
      steps: [
        { sql: insert(spec, KEY_A, outside), expect: 'ok' },
        { sql: insert(spec, KEY_A, outside), expect: 'ok' },
        { sql: insert(spec, KEY_A, outside), expect: 'ok' }
      ]
    },
    {
      id: 'independencia',
      title: 'otra clave puede tener la suya dentro de la condición',
      steps: [{ sql: insert(spec, KEY_B, inside), expect: 'ok' }]
    }
  ];
}

/**
 * Las sentencias del appendix, contadas. Sirve para dos cosas —saber si el motor emitió algo, y
 * poder decirlo por pantalla— y para NINGUNA más: el runner manda el archivo ENTERO en una sola
 * llamada, no sentencia a sentencia.
 *
 * Esa distinción costó una pasada en rojo y conviene no perderla. En MySQL el appendix son cuatro
 * sentencias planas que se comunican por una variable de usuario (`@keel_index_ddl`), y una
 * variable de usuario **muere con la sesión**. Un runner que ejecutara `CLI -e <sentencia>` una
 * por una abriría una conexión por sentencia, así que el `PREPARE` recibiría NULL y fallaría con
 * un error de sintaxis que no habla del índice ni del generador — un rojo que acusa al código
 * correcto. `spring.sql.init` sí las corre todas sobre la misma conexión, o sea que el runner
 * fiel es el que manda el archivo de una pieza; y como efecto colateral, lo que se ejecuta es
 * literalmente el contenido del archivo y no una segunda redacción suya.
 */
export function statementsOf(appendix) {
  const out = [];
  let current = [];
  for (const line of appendix.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('--')) continue;
    current.push(line);
    if (trimmed.endsWith(';')) {
      out.push(current.join('\n').trim().replace(/;$/, ''));
      current = [];
    }
  }
  return out;
}
